default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project-for-restapi

test:
  <<: *default
  database: project-for-restapi-test

production:
  <<: *default
  database: project-for-restapi-prod
